// react/src/pages/PostForm.jsx
import { useEffect, useState } from "react";
import { useParams, Link } from "react-router-dom";
import router from '../router';

export default function PostForm() {
    const [model, setModel] = useState({
        id: '',
        title: '',
        body: ''
    });

    const { id } = useParams();

    useEffect(() => {
        if (!id) {
            return;
        }
        fetch(`https://jsonplaceholder.typicode.com/posts/${ id }`).then(res => res.json()).then(post => {
            setModel(post);
        });
    }, []);

    function onSubmit(event) {
        event.preventDefault();
        if (model.id) {
            fetch(`https://jsonplaceholder.typicode.com/posts/${ model.id }`, {
                method: 'PUT',
                body: JSON.stringify(model)
            })
            .then(res => res.json())
            .then(() => {
                router.navigate('/');
            });
        } else {
            fetch('https://jsonplaceholder.typicode.com/posts', {
                method: 'POST',
                body: JSON.stringify(model)
            })
            .then(res => res.json())
            .then(() => {
                router.navigate('/');
            });
        }
    }
    return ( <div>
        <p>
            <Link to="/" className="btn btn-outline-secondary">
            Go back to list
            </Link>
        </p>
        <form onSubmit={ onSubmit }>
            <h1>{ model.id ? 'Edit Post' : 'Create new Post' }</h1>
            <div className="mb-3">
                <input
                    type="text"
                    className="form-control"
                    value={model.title}
                    onInput={event => setModel({ ...model, title: event.target.value })}
                    placeholder="Post Title"
                />
            </div>
            <div className="mb-3">
                <textarea
                    type="text"
                    className="form-control"
                    value={model.body}
                    onInput={event => setModel({ ...model, body: event.target.value })}
                    placeholder="Post Body">
                </textarea>
            </div>
            <p>
                <button
                    disabled={ !model.title || !model.body }
                    className="btn btn-success"
                    type="submit">
                    Submit
                </button>
            </p>
        </form>
    </div>);
};

// vue/src/pages/PostForm.vue
<template>
    <div>
        <p>
            <RouterLink to="/" class="btn btn-outline-secondary">
                Go back to list
            </RouterLink>
        </p>
        <!--<pre>{{ model }}</pre>-->
        <form @submit.prevent="onSubmit">
            <h1>{{ model.id ? 'Edit Post' : 'Create new Post' }}</h1>
            <div class="mb-3">
                <input
                    type="text"
                    class="form-control"
                    v-model="model.title"
                    placeholder="Post Title"
                >
            </div>
            <div class="mb-3">
                <textarea
                    type="text"
                    class="form-control"
                    v-model="model.body"
                    placeholder="Post Body">
                </textarea>
            </div>
            <p>
                <button
                    :disabled="!model.title || !model.body"
                    class="btn btn-success"
                    type="submit">
                    Submit
                </button>
            </p>
        </form>
    </div>
</template>

<script setup>
import { onMounted, ref } from "vue";
import { useRoute, useRouter } from "vue-router";

const route = useRoute();
const router = useRouter();

const model = ref({
    id: '',
    title: '',
    body: ''
});

onMounted(() => {
    if (!route.params.id) {
        return;
    }
    fetch(`https://jsonplaceholder.typicode.com/posts/${ route.params.id }`).then(res => res.json()).then(post => {
        model.value = post;
    });
});

function onSubmit() {
    if (model.value.id) {
        fetch(`https://jsonplaceholder.typicode.com/posts/${ model.value.id }`, {
            method: 'PUT',
            body: JSON.stringify(model.value)
        })
        .then(res => res.json())
        .then(() => {
            router.push('/');
        });
    } else {
        fetch('https://jsonplaceholder.typicode.com/posts', {
            method: 'POST',
            body: JSON.stringify(model.value)
        })
        .then(res => res.json())
        .then(() => {
            router.push('/');
        });
    }
}

</script>

<style>
</style>
